# Generated by Django 3.2.1 on 2021-12-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoGallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multipleimages', models.FileField(blank=True, null=True, upload_to='gallaries')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
